spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/search_engine

  liquibase:
    change-log: liquibase/changeLog.xml

  jpa:
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: false

crawler:
  max-depth: 2
  urls: https://www.7gy.ru/shkola/nachalnaya-shkola/1025-diktanty-i-teksty-dlya-spisyvaniya-bolshaya-bukva-v-imenakh-sobstvennykh.html,https://unetway.com/blog/,https://fluffynukeit.com/
#  urls: https://www.7gy.ru/shkola/nachalnaya-shkola/1025-diktanty-i-teksty-dlya-spisyvaniya-bolshaya-bukva-v-imenakh-sobstvennykh.html
  names-to-exclude: герда,мурзик,максим,оля,катя,костя,эдик